---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  apiv1_mapping
      prefix: /pvrapi/
      service: apiv1:8010
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  apiv2_mapping
      prefix: /pvrapi/
      weight: 50
      service: apiv2:8010
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
