---
apiVersion: v1
kind: Service
metadata:
  name: apiv1
  labels:
    app: apiv1
spec:
  type: ClusterIP
  selector:
    app: apiv1
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: apiv1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiv1
    spec:
      containers:
      - name: pvr-apiv1
        image: eu.gcr.io/parcel-vision/spike-ambassador-api-v1:1.0
        ports:
        - containerPort: 8010
