---
apiVersion: v1
kind: Service
metadata:
  name: apiv2
  labels:
    app: apiv2
spec:
  type: ClusterIP
  selector:
    app: apiv2
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: apiv2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiv2
    spec:
      containers:
      - name: pvr-apiv2
        image: eu.gcr.io/parcel-vision/spike-ambassador-api-v2:1.0
        ports:
        - containerPort: 8010
