---
apiVersion: v1
kind: Service
metadata:
  name: appv2
  labels:
    app: appv2
spec:
  type: ClusterIP
  selector:
    app: appv2
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: appv2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appv2
    spec:
      containers:
      - name: pvr-appv2
        image: eu.gcr.io/parcel-vision/spike-ambassador-application-v2:1.0
        ports:
        - containerPort: 8020
