---
apiVersion: v1
kind: Service
metadata:
  name: appv1
  labels:
    app: appv1
spec:
  type: ClusterIP
  selector:
    app: appv1
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: appv1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appv1
    spec:
      containers:
      - name: pvr-appv1
        image: eu.gcr.io/parcel-vision/spike-ambassador-application-v1:1.0
        ports:
        - containerPort: 8020
