---
apiVersion: v1
kind: Service
metadata:
  name: api1
  labels:
    app: api1
spec:
  type: ClusterIP
  selector:
    app: api1
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: pvr-api1
        image: eu.gcr.io/parcel-vision/spike-ambassador-api:1.0
        ports:
        - containerPort: 8010
